// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hdc_accelerator_component_Block_entry_proc_Pipeline_SimilarityOpControlLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        vector_size,
        fifo_A_dout,
        fifo_A_empty_n,
        fifo_A_read,
        fifo_B_dout,
        fifo_B_empty_n,
        fifo_B_read,
        similarity_counter_out,
        similarity_counter_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] vector_size;
input  [7:0] fifo_A_dout;
input   fifo_A_empty_n;
output   fifo_A_read;
input  [7:0] fifo_B_dout;
input   fifo_B_empty_n;
output   fifo_B_read;
output  [31:0] similarity_counter_out;
output   similarity_counter_out_ap_vld;

reg ap_idle;
reg fifo_A_read;
reg fifo_B_read;
reg similarity_counter_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln78_fu_92_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    fifo_A_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg   [0:0] icmp_ln78_reg_302;
reg    fifo_B_blk_n;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] similarity_counter_2_fu_150_p3;
reg   [31:0] similarity_counter_2_reg_306;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [0:0] tmp_1_reg_312;
reg   [0:0] tmp_2_reg_317;
reg   [0:0] tmp_3_reg_322;
reg   [0:0] tmp_4_reg_327;
reg   [0:0] tmp_5_reg_332;
reg   [0:0] tmp_6_reg_337;
wire   [31:0] similarity_counter_4_fu_223_p3;
reg   [31:0] similarity_counter_4_reg_342;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] similarity_counter_6_fu_247_p3;
reg   [31:0] similarity_counter_6_reg_348;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] similarity_counter_fu_46;
wire   [31:0] select_ln86_fu_271_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [31:0] i_fu_50;
wire   [31:0] i_4_fu_98_p2;
reg   [31:0] ap_sig_allocacmp_i_3;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] C_fu_112_p2;
wire   [0:0] trunc_ln86_fu_118_p1;
wire   [31:0] add_ln87_fu_122_p2;
wire   [31:0] similarity_counter_1_fu_128_p3;
wire   [0:0] tmp_fu_136_p3;
wire   [31:0] add_ln87_1_fu_144_p2;
wire    ap_block_pp0_stage2;
wire   [31:0] add_ln87_2_fu_206_p2;
wire   [31:0] similarity_counter_3_fu_211_p3;
wire   [31:0] add_ln87_3_fu_217_p2;
wire    ap_block_pp0_stage3;
wire   [31:0] add_ln87_4_fu_230_p2;
wire   [31:0] similarity_counter_5_fu_235_p3;
wire   [31:0] add_ln87_5_fu_241_p2;
wire   [31:0] add_ln87_6_fu_254_p2;
wire   [31:0] similarity_counter_7_fu_259_p3;
wire   [31:0] add_ln87_7_fu_265_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 similarity_counter_fu_46 = 32'd0;
#0 i_fu_50 = 32'd0;
#0 ap_done_reg = 1'b0;
end

hdc_accelerator_component_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_92_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_50 <= i_4_fu_98_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_50 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            similarity_counter_fu_46 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            similarity_counter_fu_46 <= select_ln86_fu_271_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln78_reg_302 <= icmp_ln78_fu_92_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        similarity_counter_2_reg_306 <= similarity_counter_2_fu_150_p3;
        tmp_1_reg_312 <= C_fu_112_p2[32'd2];
        tmp_2_reg_317 <= C_fu_112_p2[32'd3];
        tmp_3_reg_322 <= C_fu_112_p2[32'd4];
        tmp_4_reg_327 <= C_fu_112_p2[32'd5];
        tmp_5_reg_332 <= C_fu_112_p2[32'd6];
        tmp_6_reg_337 <= C_fu_112_p2[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        similarity_counter_4_reg_342 <= similarity_counter_4_fu_223_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        similarity_counter_6_reg_348 <= similarity_counter_6_fu_247_p3;
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_92_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_50;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fifo_A_blk_n = fifo_A_empty_n;
    end else begin
        fifo_A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fifo_A_read = 1'b1;
    end else begin
        fifo_A_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fifo_B_blk_n = fifo_B_empty_n;
    end else begin
        fifo_B_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fifo_B_read = 1'b1;
    end else begin
        fifo_B_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln78_fu_92_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        similarity_counter_out_ap_vld = 1'b1;
    end else begin
        similarity_counter_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_fu_112_p2 = (fifo_B_dout ^ fifo_A_dout);

assign add_ln87_1_fu_144_p2 = (similarity_counter_1_fu_128_p3 + 32'd1);

assign add_ln87_2_fu_206_p2 = (similarity_counter_2_reg_306 + 32'd1);

assign add_ln87_3_fu_217_p2 = (similarity_counter_3_fu_211_p3 + 32'd1);

assign add_ln87_4_fu_230_p2 = (similarity_counter_4_reg_342 + 32'd1);

assign add_ln87_5_fu_241_p2 = (similarity_counter_5_fu_235_p3 + 32'd1);

assign add_ln87_6_fu_254_p2 = (similarity_counter_6_reg_348 + 32'd1);

assign add_ln87_7_fu_265_p2 = (similarity_counter_7_fu_259_p3 + 32'd1);

assign add_ln87_fu_122_p2 = (similarity_counter_fu_46 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = (((icmp_ln78_reg_302 == 1'd0) & (fifo_B_empty_n == 1'b0)) | ((icmp_ln78_reg_302 == 1'd0) & (fifo_A_empty_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_4_fu_98_p2 = (ap_sig_allocacmp_i_3 + 32'd1);

assign icmp_ln78_fu_92_p2 = ((ap_sig_allocacmp_i_3 == vector_size) ? 1'b1 : 1'b0);

assign select_ln86_fu_271_p3 = ((tmp_6_reg_337[0:0] == 1'b1) ? similarity_counter_7_fu_259_p3 : add_ln87_7_fu_265_p2);

assign similarity_counter_1_fu_128_p3 = ((trunc_ln86_fu_118_p1[0:0] == 1'b1) ? similarity_counter_fu_46 : add_ln87_fu_122_p2);

assign similarity_counter_2_fu_150_p3 = ((tmp_fu_136_p3[0:0] == 1'b1) ? similarity_counter_1_fu_128_p3 : add_ln87_1_fu_144_p2);

assign similarity_counter_3_fu_211_p3 = ((tmp_1_reg_312[0:0] == 1'b1) ? similarity_counter_2_reg_306 : add_ln87_2_fu_206_p2);

assign similarity_counter_4_fu_223_p3 = ((tmp_2_reg_317[0:0] == 1'b1) ? similarity_counter_3_fu_211_p3 : add_ln87_3_fu_217_p2);

assign similarity_counter_5_fu_235_p3 = ((tmp_3_reg_322[0:0] == 1'b1) ? similarity_counter_4_reg_342 : add_ln87_4_fu_230_p2);

assign similarity_counter_6_fu_247_p3 = ((tmp_4_reg_327[0:0] == 1'b1) ? similarity_counter_5_fu_235_p3 : add_ln87_5_fu_241_p2);

assign similarity_counter_7_fu_259_p3 = ((tmp_5_reg_332[0:0] == 1'b1) ? similarity_counter_6_reg_348 : add_ln87_6_fu_254_p2);

assign similarity_counter_out = similarity_counter_fu_46;

assign tmp_fu_136_p3 = C_fu_112_p2[32'd1];

assign trunc_ln86_fu_118_p1 = C_fu_112_p2[0:0];

endmodule //hdc_accelerator_component_Block_entry_proc_Pipeline_SimilarityOpControlLoop
