// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hdc_accelerator_component_Block_entry28_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        sel_op,
        vector_size,
        fifo_B_dout,
        fifo_B_empty_n,
        fifo_B_read,
        fifo_A_dout,
        fifo_A_empty_n,
        fifo_A_read,
        fifo_C_din,
        fifo_C_full_n,
        fifo_C_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] sel_op;
input  [31:0] vector_size;
input  [7:0] fifo_B_dout;
input   fifo_B_empty_n;
output   fifo_B_read;
input  [7:0] fifo_A_dout;
input   fifo_A_empty_n;
output   fifo_A_read;
output  [7:0] fifo_C_din;
input   fifo_C_full_n;
output   fifo_C_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifo_B_read;
reg fifo_A_read;
reg[7:0] fifo_C_din;
reg fifo_C_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifo_B_blk_n;
reg    fifo_A_blk_n;
reg    fifo_C_blk_n;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg   [7:0] B_reg_257;
reg   [7:0] A_reg_263;
wire  signed [8:0] sub_ln47_fu_157_p2;
reg   [8:0] sub_ln47_reg_270;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_reg_275;
wire   [7:0] shl_ln47_fu_187_p2;
reg   [7:0] shl_ln47_reg_281;
wire   [7:0] lshr_ln47_fu_196_p2;
reg   [7:0] lshr_ln47_reg_286;
wire   [31:0] sub_fu_201_p2;
reg   [31:0] sub_reg_291;
wire   [8:0] conv_i_i9_i_fu_207_p2;
reg   [8:0] conv_i_i9_i_reg_296;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_done;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_idle;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_ready;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_A_read;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_B_read;
wire   [7:0] grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_din;
wire    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_write;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_done;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_idle;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_ready;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_A_read;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_B_read;
wire   [7:0] grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_din;
wire    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_write;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_done;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_idle;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_ready;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_A_read;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_B_read;
wire   [15:0] grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_similarity_counter_out;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_similarity_counter_out_ap_vld;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_done;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_idle;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_ready;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_A_read;
wire   [7:0] grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_din;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_write;
wire   [7:0] grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out;
wire    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out_ap_vld;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_done;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_idle;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_ready;
wire   [7:0] grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_din;
wire    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_write;
reg    grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg;
reg    ap_block_state1_ignore_call1;
wire    ap_CS_fsm_state5;
reg    grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg;
reg    grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [7:0] shifting_register_loc_fu_58;
reg    grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [7:0] C_fu_222_p2;
wire   [8:0] zext_ln47_fu_154_p1;
wire   [7:0] trunc_ln47_fu_168_p1;
wire   [7:0] sub_ln47_1_fu_181_p2;
wire  signed [31:0] sext_ln47_fu_164_p1;
wire   [7:0] sext_ln47cast_fu_192_p1;
wire   [7:0] overflow_block_bits_fu_214_p3;
reg    ap_block_state9_on_subcall_done;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_block_state5_on_subcall_done;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg = 1'b0;
#0 grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg = 1'b0;
#0 grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg = 1'b0;
#0 grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg = 1'b0;
#0 grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg = 1'b0;
end

hdc_accelerator_component_Block_entry28_proc1_Pipeline_BundlingOpControlLoop grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start),
    .ap_done(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_done),
    .ap_idle(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_idle),
    .ap_ready(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_B_read),
    .fifo_C_din(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_write),
    .vector_size(vector_size)
);

hdc_accelerator_component_Block_entry28_proc1_Pipeline_BindingOpControlLoop grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start),
    .ap_done(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_done),
    .ap_idle(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_idle),
    .ap_ready(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_B_read),
    .fifo_C_din(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_write),
    .vector_size(vector_size)
);

hdc_accelerator_component_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start),
    .ap_done(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_done),
    .ap_idle(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_idle),
    .ap_ready(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_ready),
    .vector_size(vector_size),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_B_read),
    .similarity_counter_out(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_similarity_counter_out),
    .similarity_counter_out_ap_vld(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_similarity_counter_out_ap_vld)
);

hdc_accelerator_component_Block_entry28_proc1_Pipeline_PermutationOpControlLoop grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start),
    .ap_done(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_done),
    .ap_idle(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_idle),
    .ap_ready(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_A_read),
    .fifo_C_din(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_write),
    .A(A_reg_263),
    .zext_ln49(B_reg_257),
    .sub(sub_reg_291),
    .sext_ln52(conv_i_i9_i_reg_296),
    .sext_ln47(sub_ln47_reg_270),
    .icmp_ln47(tmp_reg_275),
    .shifting_register_out(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out),
    .shifting_register_out_ap_vld(grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out_ap_vld)
);

hdc_accelerator_component_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start),
    .ap_done(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_done),
    .ap_idle(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_idle),
    .ap_ready(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_ready),
    .fifo_C_din(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_write),
    .similarity_counter_reload(grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_similarity_counter_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_ready == 1'b1)) begin
            grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_ready == 1'b1)) begin
            grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_ready == 1'b1)) begin
            grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_ready == 1'b1)) begin
            grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_ready == 1'b1)) begin
            grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        A_reg_263 <= fifo_A_dout;
        B_reg_257 <= fifo_B_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_i_i9_i_reg_296 <= conv_i_i9_i_fu_207_p2;
        lshr_ln47_reg_286 <= lshr_ln47_fu_196_p2;
        shl_ln47_reg_281 <= shl_ln47_fu_187_p2;
        sub_ln47_reg_270 <= sub_ln47_fu_157_p2;
        sub_reg_291 <= sub_fu_201_p2;
        tmp_reg_275 <= sub_ln47_fu_157_p2[32'd8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out_ap_vld == 1'b1))) begin
        shifting_register_loc_fu_58 <= grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_shifting_register_out;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fifo_C_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state9_on_subcall_done)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        fifo_A_blk_n = fifo_A_empty_n;
    end else begin
        fifo_A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        fifo_A_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_A_read = grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_A_read;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fifo_A_read = grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_A_read;
    end else if (((sel_op == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_A_read = grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_A_read;
    end else if (((sel_op == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_A_read = grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_A_read;
    end else begin
        fifo_A_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        fifo_B_blk_n = fifo_B_empty_n;
    end else begin
        fifo_B_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        fifo_B_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fifo_B_read = grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_fifo_B_read;
    end else if (((sel_op == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_B_read = grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_B_read;
    end else if (((sel_op == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_B_read = grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_B_read;
    end else begin
        fifo_B_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fifo_C_blk_n = fifo_C_full_n;
    end else begin
        fifo_C_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((fifo_C_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_C_din = C_fu_222_p2;
    end else if (((sel_op == 2'd3) & (1'b1 == ap_CS_fsm_state9))) begin
        fifo_C_din = grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_din;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_C_din = grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_din;
    end else if (((sel_op == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_C_din = grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_din;
    end else if (((sel_op == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_C_din = grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_din;
    end else begin
        fifo_C_din = grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_din;
    end
end

always @ (*) begin
    if (((fifo_C_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_C_write = 1'b1;
    end else if (((sel_op == 2'd3) & (1'b1 == ap_CS_fsm_state9))) begin
        fifo_C_write = grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_fifo_C_write;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_C_write = grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_fifo_C_write;
    end else if (((sel_op == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_C_write = grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_fifo_C_write;
    end else if (((sel_op == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        fifo_C_write = grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_fifo_C_write;
    end else begin
        fifo_C_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1) & ((sel_op == 2'd0) | (sel_op == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0))) & (sel_op == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((fifo_C_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & ((sel_op == 2'd0) | (sel_op == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_fu_222_p2 = (shifting_register_loc_fu_58 | overflow_block_bits_fu_214_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1_ignore_call1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((sel_op == 2'd2) & (fifo_A_empty_n == 1'b0)) | ((sel_op == 2'd2) & (fifo_B_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_on_subcall_done = (((grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_done == 1'b0) & (sel_op == 2'd1)) | ((sel_op == 2'd0) & (grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state9_on_subcall_done = ((sel_op == 2'd3) & (grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_done == 1'b0));
end

assign conv_i_i9_i_fu_207_p2 = ($signed(9'd0) - $signed(sub_ln47_fu_157_p2));

assign grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start = grp_Block_entry28_proc1_Pipeline_BindingOpControlLoop_fu_109_ap_start_reg;

assign grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start = grp_Block_entry28_proc1_Pipeline_BundlingOpControlLoop_fu_97_ap_start_reg;

assign grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start = grp_Block_entry28_proc1_Pipeline_PermutationOpControlLoop_fu_132_ap_start_reg;

assign grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start = grp_Block_entry28_proc1_Pipeline_SimilarityOpControlLoop_fu_121_ap_start_reg;

assign grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start = grp_Block_entry28_proc1_Pipeline_SimilarityOpWriteLoop_fu_147_ap_start_reg;

assign lshr_ln47_fu_196_p2 = A_reg_263 >> sext_ln47cast_fu_192_p1;

assign overflow_block_bits_fu_214_p3 = ((tmp_reg_275[0:0] == 1'b1) ? shl_ln47_reg_281 : lshr_ln47_reg_286);

assign sext_ln47_fu_164_p1 = sub_ln47_fu_157_p2;

assign sext_ln47cast_fu_192_p1 = sext_ln47_fu_164_p1[7:0];

assign shl_ln47_fu_187_p2 = A_reg_263 << sub_ln47_1_fu_181_p2;

assign sub_fu_201_p2 = ($signed(vector_size) + $signed(32'd4294967295));

assign sub_ln47_1_fu_181_p2 = (8'd0 - trunc_ln47_fu_168_p1);

assign sub_ln47_fu_157_p2 = (9'd8 - zext_ln47_fu_154_p1);

assign trunc_ln47_fu_168_p1 = sub_ln47_fu_157_p2[7:0];

assign zext_ln47_fu_154_p1 = B_reg_257;

endmodule //hdc_accelerator_component_Block_entry28_proc1
