// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hdc_accelerator_component_Block_entry28_proc1_Pipeline_PermutationOpControlLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fifo_A_dout,
        fifo_A_empty_n,
        fifo_A_read,
        fifo_C_din,
        fifo_C_full_n,
        fifo_C_write,
        A,
        zext_ln49,
        sub,
        sext_ln52,
        sext_ln47,
        icmp_ln47,
        shifting_register_out,
        shifting_register_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] fifo_A_dout;
input   fifo_A_empty_n;
output   fifo_A_read;
output  [7:0] fifo_C_din;
input   fifo_C_full_n;
output   fifo_C_write;
input  [7:0] A;
input  [7:0] zext_ln49;
input  [31:0] sub;
input  [8:0] sext_ln52;
input  [8:0] sext_ln47;
input  [0:0] icmp_ln47;
output  [7:0] shifting_register_out;
output   shifting_register_out_ap_vld;

reg ap_idle;
reg fifo_A_read;
reg fifo_C_write;
reg shifting_register_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln52_reg_233;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln52_fu_137_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    fifo_A_blk_n;
wire    ap_block_pp0_stage0;
reg    fifo_C_blk_n;
reg    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln47_cast_fu_116_p1;
reg  signed [31:0] sext_ln47_cast_reg_223;
wire  signed [31:0] sext_ln52_cast_fu_120_p1;
reg  signed [31:0] sext_ln52_cast_reg_228;
wire   [7:0] C_fu_188_p2;
reg   [7:0] C_reg_237;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [31:0] i_2_fu_52;
wire   [31:0] i_5_fu_143_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i;
reg   [7:0] A_1_fu_56;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] shl_ln59_fu_157_p2;
wire   [7:0] sext_ln52_castcast_fu_163_p1;
wire   [7:0] sext_ln47_castcast_fu_172_p1;
wire   [7:0] shl_ln57_fu_166_p2;
wire   [7:0] lshr_ln57_fu_175_p2;
wire   [7:0] select_ln57_fu_181_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hdc_accelerator_component_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            A_1_fu_56 <= A;
        end else if (((icmp_ln52_reg_233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            A_1_fu_56 <= fifo_A_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_52 <= i_5_fu_143_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_52 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln52_reg_233 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_reg_237 <= C_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln52_reg_233 <= icmp_ln52_fu_137_p2;
        sext_ln47_cast_reg_223 <= sext_ln47_cast_fu_116_p1;
        sext_ln52_cast_reg_228 <= sext_ln52_cast_fu_120_p1;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln52_reg_233 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 32'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln52_reg_233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_A_blk_n = fifo_A_empty_n;
    end else begin
        fifo_A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln52_reg_233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_A_read = 1'b1;
    end else begin
        fifo_A_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fifo_C_blk_n = fifo_C_full_n;
    end else begin
        fifo_C_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fifo_C_write = 1'b1;
    end else begin
        fifo_C_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln52_reg_233 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shifting_register_out_ap_vld = 1'b1;
    end else begin
        shifting_register_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_fu_188_p2 = (shl_ln59_fu_157_p2 | select_ln57_fu_181_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((fifo_C_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln52_reg_233 == 1'd0) & (fifo_A_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((fifo_C_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln52_reg_233 == 1'd0) & (fifo_A_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((fifo_C_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln52_reg_233 == 1'd0) & (fifo_A_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln52_reg_233 == 1'd0) & (fifo_A_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (fifo_C_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign fifo_C_din = C_reg_237;

assign i_5_fu_143_p2 = (ap_sig_allocacmp_i + 32'd1);

assign icmp_ln52_fu_137_p2 = ((ap_sig_allocacmp_i == sub) ? 1'b1 : 1'b0);

assign lshr_ln57_fu_175_p2 = fifo_A_dout >> sext_ln47_castcast_fu_172_p1;

assign select_ln57_fu_181_p3 = ((icmp_ln47[0:0] == 1'b1) ? shl_ln57_fu_166_p2 : lshr_ln57_fu_175_p2);

assign sext_ln47_cast_fu_116_p1 = $signed(sext_ln47);

assign sext_ln47_castcast_fu_172_p1 = sext_ln47_cast_reg_223[7:0];

assign sext_ln52_cast_fu_120_p1 = $signed(sext_ln52);

assign sext_ln52_castcast_fu_163_p1 = sext_ln52_cast_reg_228[7:0];

assign shifting_register_out = shl_ln59_fu_157_p2;

assign shl_ln57_fu_166_p2 = fifo_A_dout << sext_ln52_castcast_fu_163_p1;

assign shl_ln59_fu_157_p2 = A_1_fu_56 << zext_ln49;

endmodule //hdc_accelerator_component_Block_entry28_proc1_Pipeline_PermutationOpControlLoop
