// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

module hdc_accelerator_component_partset_32ns_32ns_8ns_5ns_32_1_1 (sel,din,value,dout);

parameter ADDRWIDTH = 5;
parameter DATAWIDTH = 32;
parameter DATA1WIDTH = 8;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
input [DATA1WIDTH-1:0] value;
output [DATAWIDTH-1:0] dout;

reg [DATAWIDTH+DATA1WIDTH-1:0] din_tmp;

wire [DATAWIDTH-1:0] dout_tmp;



always @ (*) 
begin
    din_tmp = { 8'b00000000 , din };
    din_tmp[sel+DATA1WIDTH-1 -: DATA1WIDTH] = value;
end

assign dout_tmp = din_tmp[DATAWIDTH-1:0];




assign dout = dout_tmp;




endmodule
