// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hdc_accelerator_component_hdc_accelerator_component,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-fgg484-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.259000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=442,HLS_SYN_LUT=1446,HLS_VERSION=2023_1_1}" *)

module hdc_accelerator_component (
        vector_size,
        sel_op,
        fifo_A_dout,
        fifo_A_empty_n,
        fifo_A_read,
        fifo_B_dout,
        fifo_B_empty_n,
        fifo_B_read,
        fifo_C_din,
        fifo_C_full_n,
        fifo_C_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] vector_size;
input  [1:0] sel_op;
input  [7:0] fifo_A_dout;
input   fifo_A_empty_n;
output   fifo_A_read;
input  [7:0] fifo_B_dout;
input   fifo_B_empty_n;
output   fifo_B_read;
output  [7:0] fifo_C_din;
input   fifo_C_full_n;
output   fifo_C_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_entry28_proc1_U0_ap_start;
wire    Block_entry28_proc1_U0_ap_done;
wire    Block_entry28_proc1_U0_ap_continue;
wire    Block_entry28_proc1_U0_ap_idle;
wire    Block_entry28_proc1_U0_ap_ready;
wire    Block_entry28_proc1_U0_fifo_B_read;
wire    Block_entry28_proc1_U0_fifo_A_read;
wire   [7:0] Block_entry28_proc1_U0_fifo_C_din;
wire    Block_entry28_proc1_U0_fifo_C_write;

hdc_accelerator_component_Block_entry28_proc1 Block_entry28_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_entry28_proc1_U0_ap_start),
    .ap_done(Block_entry28_proc1_U0_ap_done),
    .ap_continue(Block_entry28_proc1_U0_ap_continue),
    .ap_idle(Block_entry28_proc1_U0_ap_idle),
    .ap_ready(Block_entry28_proc1_U0_ap_ready),
    .sel_op(sel_op),
    .vector_size(vector_size),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(Block_entry28_proc1_U0_fifo_B_read),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(Block_entry28_proc1_U0_fifo_A_read),
    .fifo_C_din(Block_entry28_proc1_U0_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(Block_entry28_proc1_U0_fifo_C_write)
);

assign Block_entry28_proc1_U0_ap_continue = 1'b1;

assign Block_entry28_proc1_U0_ap_start = ap_start;

assign ap_done = Block_entry28_proc1_U0_ap_done;

assign ap_idle = Block_entry28_proc1_U0_ap_idle;

assign ap_ready = Block_entry28_proc1_U0_ap_ready;

assign fifo_A_read = Block_entry28_proc1_U0_fifo_A_read;

assign fifo_B_read = Block_entry28_proc1_U0_fifo_B_read;

assign fifo_C_din = Block_entry28_proc1_U0_fifo_C_din;

assign fifo_C_write = Block_entry28_proc1_U0_fifo_C_write;

endmodule //hdc_accelerator_component
