// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hdc_accelerator_component_Block_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        sel_op,
        fifo_A_dout,
        fifo_A_empty_n,
        fifo_A_read,
        vector_size,
        fifo_C_din,
        fifo_C_full_n,
        fifo_C_write,
        fifo_B_dout,
        fifo_B_empty_n,
        fifo_B_read
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] sel_op;
input  [7:0] fifo_A_dout;
input   fifo_A_empty_n;
output   fifo_A_read;
input  [31:0] vector_size;
output  [7:0] fifo_C_din;
input   fifo_C_full_n;
output   fifo_C_write;
input  [7:0] fifo_B_dout;
input   fifo_B_empty_n;
output   fifo_B_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifo_A_read;
reg[7:0] fifo_C_din;
reg fifo_C_write;
reg fifo_B_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifo_A_blk_n;
wire    ap_CS_fsm_state3;
reg    fifo_C_blk_n;
wire    ap_CS_fsm_state6;
reg   [1:0] sel_op_read_reg_325;
reg   [31:0] vector_size_read_reg_317;
reg    ap_block_state1;
wire   [1:0] sel_op_read_read_fu_74_p2;
reg   [7:0] A_reg_347;
reg   [0:0] tmp_reg_357;
wire    ap_CS_fsm_state4;
wire   [31:0] trunc_ln49_fu_220_p1;
reg   [31:0] trunc_ln49_reg_363;
wire   [31:0] sub_ln49_1_fu_225_p2;
reg   [31:0] sub_ln49_1_reg_368;
wire   [7:0] shl_ln49_fu_236_p2;
reg   [7:0] shl_ln49_reg_373;
wire   [7:0] lshr_ln49_fu_245_p2;
reg   [7:0] lshr_ln49_reg_378;
wire   [31:0] sub30_fu_250_p2;
reg   [31:0] sub30_reg_383;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_done;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_idle;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_ready;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_fifo_B_read;
wire   [31:0] grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out;
wire    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out_ap_vld;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_done;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_idle;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_ready;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_A_read;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_B_read;
wire   [7:0] grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_din;
wire    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_write;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_done;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_idle;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_ready;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_A_read;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_B_read;
wire   [7:0] grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_din;
wire    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_write;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_done;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_idle;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_ready;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_A_read;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_B_read;
wire   [31:0] grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_similarity_counter_out;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_similarity_counter_out_ap_vld;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_done;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_idle;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_ready;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_A_read;
wire   [7:0] grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_din;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_write;
wire   [7:0] grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out;
wire    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out_ap_vld;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_done;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_idle;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_ready;
wire   [7:0] grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_din;
wire    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_write;
reg    grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg;
reg    grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [7:0] shl_ln61_loc_fu_56;
reg    grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [7:0] C_fu_278_p2;
reg    ap_block_state6;
wire   [32:0] zext_ln49_fu_201_p1;
wire   [32:0] sub_ln49_fu_205_p2;
wire   [7:0] sub_ln49_1cast_fu_232_p1;
wire   [7:0] trunc_ln49cast_fu_241_p1;
wire   [7:0] overflow_block_bits_fu_273_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_block_state7_on_subcall_done;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg = 1'b0;
#0 grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg = 1'b0;
#0 grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg = 1'b0;
#0 grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg = 1'b0;
#0 grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg = 1'b0;
#0 grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg = 1'b0;
end

hdc_accelerator_component_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_ready),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_fifo_B_read),
    .shift_value_out(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out),
    .shift_value_out_ap_vld(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out_ap_vld)
);

hdc_accelerator_component_Block_entry_proc_Pipeline_BundlingOpControlLoop grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_B_read),
    .fifo_C_din(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_write),
    .vector_size(vector_size_read_reg_317)
);

hdc_accelerator_component_Block_entry_proc_Pipeline_BindingOpControlLoop grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_B_read),
    .fifo_C_din(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_write),
    .vector_size(vector_size_read_reg_317)
);

hdc_accelerator_component_Block_entry_proc_Pipeline_SimilarityOpControlLoop grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_ready),
    .vector_size(vector_size_read_reg_317),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_A_read),
    .fifo_B_dout(fifo_B_dout),
    .fifo_B_empty_n(fifo_B_empty_n),
    .fifo_B_read(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_B_read),
    .similarity_counter_out(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_similarity_counter_out),
    .similarity_counter_out_ap_vld(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_similarity_counter_out_ap_vld)
);

hdc_accelerator_component_Block_entry_proc_Pipeline_PermutationOpControlLoop grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_ready),
    .fifo_A_dout(fifo_A_dout),
    .fifo_A_empty_n(fifo_A_empty_n),
    .fifo_A_read(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_A_read),
    .fifo_C_din(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_write),
    .A_3(A_reg_347),
    .shift_value_reload(grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out),
    .sub30(sub30_reg_383),
    .sub_ln49_1(sub_ln49_1_reg_368),
    .empty_18(trunc_ln49_reg_363),
    .empty(tmp_reg_357),
    .shl_ln61_out(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out),
    .shl_ln61_out_ap_vld(grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out_ap_vld)
);

hdc_accelerator_component_Block_entry_proc_Pipeline_SimilarityOpWriteLoop grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start),
    .ap_done(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_done),
    .ap_idle(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_idle),
    .ap_ready(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_ready),
    .fifo_C_din(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_din),
    .fifo_C_full_n(fifo_C_full_n),
    .fifo_C_write(grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_write),
    .similarity_counter_reload(grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_similarity_counter_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if (((sel_op_read_read_fu_74_p2 == 2'd0) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((sel_op_read_read_fu_74_p2 == 2'd1) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg <= 1'b0;
    end else begin
        if (((sel_op_read_read_fu_74_p2 == 2'd2) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if (((sel_op_read_read_fu_74_p2 == 2'd3) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_ready == 1'b1)) begin
            grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((fifo_A_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        A_reg_347 <= fifo_A_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lshr_ln49_reg_378 <= lshr_ln49_fu_245_p2;
        shl_ln49_reg_373 <= shl_ln49_fu_236_p2;
        sub30_reg_383 <= sub30_fu_250_p2;
        sub_ln49_1_reg_368 <= sub_ln49_1_fu_225_p2;
        tmp_reg_357 <= sub_ln49_fu_205_p2[32'd32];
        trunc_ln49_reg_363 <= trunc_ln49_fu_220_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        sel_op_read_reg_325 <= sel_op;
        vector_size_read_reg_317 <= vector_size;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out_ap_vld == 1'b1))) begin
        shl_ln61_loc_fu_56 <= grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_shl_ln61_out;
    end
end

always @ (*) begin
    if ((grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fifo_A_empty_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state7_on_subcall_done)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_A_blk_n = fifo_A_empty_n;
    end else begin
        fifo_A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((fifo_A_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        fifo_A_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        fifo_A_read = grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_A_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        fifo_A_read = grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_A_read;
    end else if (((sel_op_read_reg_325 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_A_read = grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_A_read;
    end else if (((sel_op_read_reg_325 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_A_read = grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_A_read;
    end else begin
        fifo_A_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        fifo_B_read = grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_fifo_B_read;
    end else if (((sel_op_read_reg_325 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_B_read = grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_B_read;
    end else if (((sel_op_read_reg_325 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_B_read = grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_B_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fifo_B_read = grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_fifo_B_read;
    end else begin
        fifo_B_read = 1'b0;
    end
end

always @ (*) begin
    if (((sel_op_read_reg_325 == 2'd2) & (1'b1 == ap_CS_fsm_state6))) begin
        fifo_C_blk_n = fifo_C_full_n;
    end else begin
        fifo_C_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (sel_op_read_reg_325 == 2'd2) & (1'b1 == ap_CS_fsm_state6))) begin
        fifo_C_din = C_fu_278_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        fifo_C_din = grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_din;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        fifo_C_din = grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_din;
    end else if (((sel_op_read_reg_325 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_C_din = grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_din;
    end else if (((sel_op_read_reg_325 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_C_din = grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_din;
    end else begin
        fifo_C_din = grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (sel_op_read_reg_325 == 2'd2) & (1'b1 == ap_CS_fsm_state6))) begin
        fifo_C_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        fifo_C_write = grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_fifo_C_write;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        fifo_C_write = grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_fifo_C_write;
    end else if (((sel_op_read_reg_325 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_C_write = grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_fifo_C_write;
    end else if (((sel_op_read_reg_325 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        fifo_C_write = grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_fifo_C_write;
    end else begin
        fifo_C_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((sel_op_read_read_fu_74_p2 == 2'd3) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((sel_op_read_read_fu_74_p2 == 2'd0) | (sel_op_read_read_fu_74_p2 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((sel_op_read_read_fu_74_p2 == 2'd2) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((fifo_A_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7) & ((sel_op_read_reg_325 == 2'd0) | (sel_op_read_reg_325 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_fu_278_p2 = (shl_ln61_loc_fu_56 | overflow_block_bits_fu_273_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((sel_op_read_reg_325 == 2'd2) & (fifo_C_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_on_subcall_done = (((sel_op_read_reg_325 == 2'd0) & (grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_done == 1'b0)) | ((sel_op_read_reg_325 == 2'd1) & (grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_done == 1'b0)));
end

assign grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start = grp_Block_entry_proc_Pipeline_BindingOpControlLoop_fu_112_ap_start_reg;

assign grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start = grp_Block_entry_proc_Pipeline_BundlingOpControlLoop_fu_100_ap_start_reg;

assign grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start = grp_Block_entry_proc_Pipeline_PermutationOpControlLoop_fu_135_ap_start_reg;

assign grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start = grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_ap_start_reg;

assign grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start = grp_Block_entry_proc_Pipeline_SimilarityOpControlLoop_fu_124_ap_start_reg;

assign grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start = grp_Block_entry_proc_Pipeline_SimilarityOpWriteLoop_fu_150_ap_start_reg;

assign lshr_ln49_fu_245_p2 = A_reg_347 >> trunc_ln49cast_fu_241_p1;

assign overflow_block_bits_fu_273_p3 = ((tmp_reg_357[0:0] == 1'b1) ? shl_ln49_reg_373 : lshr_ln49_reg_378);

assign sel_op_read_read_fu_74_p2 = sel_op;

assign shl_ln49_fu_236_p2 = A_reg_347 << sub_ln49_1cast_fu_232_p1;

assign sub30_fu_250_p2 = ($signed(vector_size_read_reg_317) + $signed(32'd4294967295));

assign sub_ln49_1_fu_225_p2 = (32'd0 - trunc_ln49_fu_220_p1);

assign sub_ln49_1cast_fu_232_p1 = sub_ln49_1_fu_225_p2[7:0];

assign sub_ln49_fu_205_p2 = (33'd8 - zext_ln49_fu_201_p1);

assign trunc_ln49_fu_220_p1 = sub_ln49_fu_205_p2[31:0];

assign trunc_ln49cast_fu_241_p1 = trunc_ln49_fu_220_p1[7:0];

assign zext_ln49_fu_201_p1 = grp_Block_entry_proc_Pipeline_PermutationOpShiftReadLoop_fu_93_shift_value_out;

endmodule //hdc_accelerator_component_Block_entry_proc
